leaderboard:
  fields:
  - Author
  - Language
  - Word
  - Score
  - Time (ms)
  - Notes
  solutionField: Score
  rankingField: Time (ms)
oops:
  fields:
  - Author
  - Word
  - Score
solution:
  value: 0 # irrelevant for this challenge, but needs to be set to something
  type: int
testCount: 5